@extends('layouts.app')

@section('content')

  <div class="h-50v" role="main"><div class="section py-5" style="margin-top: 80px"><div class="container"><!----> <div class="d-flex justify-content-center flex-column position-relative"><p class="small">ARTICLE
    | <span class="text-muted">JANUARY 22, 2020</span></p> <h1 class="text-catalina mb-3 pb-3 border-bottom">
    6 ways to stay fit in 2020
  </h1> <div><p><img class="alignnone  wp-image-5472" src="https://www.armpension.com/wp-content/uploads/newsletter-img-2-300x183.jpg" alt="" width="400" height="244"></p><p>They say health is wealth and the sure-fire way to ensure that your health is up to par this New Year is by maintaining a fit body. Here are ways to achieve just that.</p><p><strong>Be intentional</strong></p><p>Make it a point to take your wellness seriously by intentionally forming new habits that will help you make living healthy a lifestyle. Set a workout alarm. Buy a scale to monitor your weight. Unearth that portion control plate you dumped. Just make sure to be intentional.</p><p><strong>Create a workout schedule/plan</strong></p><p>He who fails to plan plans to fail. Planning your workout helps you manage the time you dedicate to it and also helps you stay committed to doing it. You can’t hit the gym or show up in your workout gear at home with no plan of action. Create a monthly workout plan with your goal in mind. Where you can’t create one for yourself, seek out a fitness trainer to help you create one.</p><p><strong>Find a fitness buddy</strong></p><p>Fitness buddies motivate one to work out and encourage them to show up on the days they otherwise wouldn’t. Find a fitness buddy preferably one who is a lot more committed to fitness than you are.</p><p><strong>Choose your food wisely</strong></p><p>It may be hard to choose healthier meal options but your health will thank you for it. Studies show a rapid hike in the number of obese people all over the world who don’t even know they are obese. Don’t be counted among those numbers.</p><p><strong>Get ample rest</strong></p><p>Even engines break down when used incessantly with no break how much more your body. Get ample rest each day even if it means taking cat naps of between 20-30 minutes in between your day. It will help improve your focus and productivity.</p><p><strong>Go for regular checkups </strong></p><p>Don’t assume that all your body mechanics are functioning at their optimum. Schedule about two visits a year with your doctor to ensure you’re doing great fitness-wise.</p><p>&nbsp;</p><p>When you are fit, you can ace all the goals you’ve set for the year and beyond!</p></div> <div><button class="btn btn-small bg-claret text-white mt-3"><i class="fa fa-arrow-alt-circle-left px-3"></i> Back to Posts</button></div></div></div></div></div>

@endsection