@extends('layouts.app')

@section('content')

<div class="h-50v" role="main"><div class="section py-5" style="margin-top: 80px"><div class="container"><!----> <div class="d-flex justify-content-center flex-column position-relative"><p class="small">ARTICLE
    | <span class="text-muted">SEPTEMBER 23, 2019</span></p> <h1 class="text-catalina mb-3 pb-3 border-bottom">
    Can you fix these?
  </h1> <div><p>The holiday is over and it’s time to go back to school for another semester but Jim is still not ready. He knows that each semester brings him closer to graduation and ultimately soon he will be thrown into the job market. The past 7 months had swept by like a breeze and he is determined to make sure he accounts for the remaining 4 months especially as it concerns his future.</p><p><img class="alignnone size-medium wp-image-5366" src="https://www.armpension.com/wp-content/uploads/NEWSLETTER-IMAGE-300x198.jpg" alt="" width="300" height="198"></p><p>He decides to begin with fixing the following:</p><p><strong>Clean out his online representation:</strong> In this day and age, one of the worst ways students can damage their future careers is by sharing the wrong kind of information online. Jim’s older brother had told him to assume that everything he posts online will be available to prospective employers, clients, or investors – because no kidding, these people actually go to the internet to research potential employees or partners. He will build a public-ready profile and under his own name too (not nick-names).</p><p><strong>Gain knowledge:</strong>&nbsp;Jim decided not to wait until he graduates to know what he wants to do career-wise. He decided not to wait until he is called for an interview to learn how to respond to questions. He also decided not to wait until he must choose his&nbsp;<a href="https://www.armpension.com/">Pension Fund Administrators</a>&nbsp;to make a choice. He will start his research now to know what he will need to make informed decisions when the time comes.</p><p><strong>Build a network:</strong>&nbsp;Now was the time for Jim to start making connections. He will email people in fields he is interested in even if it’s just to say, “I read your book, or I admire your work”, join professional organizations and attend conferences. No more spending all his time partying or strolling the streets of social media aimlessly.</p><p><strong>Read more books:</strong> Asides from his course-related books, Jim resolved to read more books in all fields especially self-help books. He knows what they say about readers being leaders and he intends to lead in some way, someday.</p><p><strong>Save more</strong>: As an avid artist, Jim made some money on the side with his talent to support what his parents and relatives give him for school. He also realized that he had not managed to save a dime of it since this year, so he made a list of all that zaps his money and crossed out the frivolities. He wants to enter 2020 a more focused and tad richer version of himself.</p><p>It’s a new semester! Be like Jim and not don’t just enjoy life on campus but also prepare for life in the real world when you graduate.</p><p>&nbsp;</p></div> <div><button class="btn btn-small bg-claret text-white mt-3"><i class="fa fa-arrow-alt-circle-left px-3"></i> Back to Posts</button></div></div></div></div></div>

@endsection