@extends('layouts.app')

@section('content')

<div class="h-50v" role="main"><div class="section py-5" style="margin-top: 80px"><div class="container"><!----> <div class="d-flex justify-content-center flex-column position-relative"><p class="small">ARTICLE
    | <span class="text-muted">AUGUST 1, 2019</span></p> <h1 class="text-catalina mb-3 pb-3 border-bottom">
    PFAs encourage contributors to participate in the Data Recapturing Exercise
  </h1> <div><p>ARM Pension ably represented by the Managing Director Mr.Wale Odutola was at the Media Parley organized by the Pension Fund Operators Association of Nigeria (PenOp) on July 30, 2019, in Lagos. The event was held to enable stakeholders give an update on activities and performance of the Pension industry.</p><p><img class="alignnone wp-image-5318" src="https://www.armpension.com/wp-content/uploads/cropped-IMG-0892-780x405-300x156.jpg" alt="" width="478" height="248"></p><p>Among issues tackled are the ongoing Data recapturing of pension clients which according to reports by BusinessDay Newspaper, the president, Mrs Adereonke&nbsp; Adedeji pointed out its necessity in enhancing the credibility of the new pension scheme as well as the protection of pension clients against cybercrime as well as fraudulent intents and activities. The report stated that she disclosed the compulsory nature of the exercise for all Retirement Savings Account (RSA) holders while urging contributors to make haste in participating fully in the exercise.</p><p>It will be recalled that since this year, ARM Pension in line with the National Pension Commission (PenCom)’s directive has made progress in encouraging her clients to participate in the data recapturing process in order to ensure accuracy of the contributors’ database. This exercise is still ongoing.</p><p>Another matter discussed at the event was the recently launched <a href="http://www.armpension.com/micropensions">Micro Pension Scheme</a> and the performance of the process since its announcement to the general public.</p><p>Click <a href="http://www.armpension.com/micropensions">here</a> to learn more about the Micro Pension Scheme.</p></div> <div><button class="btn btn-small bg-claret text-white mt-3"><i class="fa fa-arrow-alt-circle-left px-3"></i> Back to Posts</button></div></div></div></div></div>

@endsection