@extends('layouts.app')

@section('content')

  <div class="h-50v" role="main"><div class="section py-5" style="margin-top: 80px"><div class="container"><!----> <div class="d-flex justify-content-center flex-column position-relative"><p class="small">ARTICLE
    | <span class="text-muted">NOVEMBER 21, 2019</span></p> <h1 class="text-catalina mb-3 pb-3 border-bottom">
    The Good, The Fun and The Winnings
  </h1> <div><p></p><h4>Here are 4 things you will experience at Run For The Future</h4><p></p><p><strong>Dance magic</strong></p><p><img class="alignnone size-medium wp-image-5425" src="https://www.armpension.com/wp-content/uploads/Dance-image-300x198.jpg" alt="" width="300" height="198"></p><p>You’ve probably danced at the previous seasons of the Run For The Future, but get ready – what we have in store is dance like you’ve not seen before. When the music comes on after the run proper, you’ll experience magic disguised as dance. Oh, you’ll have fun till you drop.</p><p><strong>Fitness on track</strong></p><p><img class="alignnone size-medium wp-image-5424" src="https://www.armpension.com/wp-content/uploads/runnerss-300x189.jpg" alt="" width="300" height="189"></p><p>What better way to improve your fitness than to test your strength on the run track? With the Run For The Future, it’s either you win, or you win! There’s nothing to lose but plenty to win when you <a href="http://www.armpension.com/rftf">register to run</a>.</p><p><strong>Truck-Load of prizes to be won</strong></p><p><img class="alignnone size-medium wp-image-5426" src="https://www.armpension.com/wp-content/uploads/medal-image-300x189.jpg" alt="" width="300" height="189"></p><p>We’re not talking small-time prizes here people! We’re talking prizes that will have you grinning from ear to ear with the knowledge of what you will do with them. Simply blaze trails on the track, come out tops and voila - you’ve bagged yourself an impressive prize or prizes as the case may be.</p><p><strong>Networking on a whole new level</strong></p><p><img class="alignnone size-medium wp-image-5427" src="https://www.armpension.com/wp-content/uploads/runners-image-300x187.jpg" alt="" width="300" height="187"></p><p>Where better to meet potential besties, fit buddies, business connections and erhmm … maybe soul mate than at the venue where thousands of people from all works of life gather to run for a better future? Trust us; you will meet people at this run that will stay in your life for a long time.</p><p>Let’s stop at four even though we know there is so much more you will gain when you attend the run.</p><p>First things first though, <a href="http://www.armpension.com/rftf">click here to register for the run</a> and tell your friends to register as well and save the date. It’s on November 30! See you there.</p></div> <div><button class="btn btn-small bg-claret text-white mt-3"><i class="fa fa-arrow-alt-circle-left px-3"></i> Back to Posts</button></div></div></div></div></div>

@endsection