@extends('layouts.app')

@section('content')

<div class="h-50v" role="main"><div class="section py-5" style="margin-top: 80px"><div class="container"><!----> <div class="d-flex justify-content-center flex-column position-relative"><p class="small">ARTICLE
    | <span class="text-muted">OCTOBER 23, 2019</span></p> <h1 class="text-catalina mb-3 pb-3 border-bottom">
    Two crazy runners
  </h1> <div><p><img class="alignnone  wp-image-5383" src="https://www.armpension.com/wp-content/uploads/image002-2-300x148.jpg" alt="" width="359" height="177"></p><p>&nbsp;</p><p>There he was again. Even in the rain, Chimdi couldn’t understand why this fellow always had to run along the same path as he almost every day. Worse, he was just totally unfriendly…never acknowledging the runner’s nod Chimdi gave him whenever they passed each other while running.</p><p>Jerome moved into the estate 4 months earlier and loved how accessible routes were to make his run a smooth affair. He also loved that he could run in peace without having to exchange pleasantries and maybe even slow down just to talk with someone. He hated going to the gym or exercising and then spending a good portion of the time he could use in putting in more energy, gisting. It just wasn’t his style.</p><p>So whenever he ran along the estate route, he plugged his ear pod and blasted his Jamz for motivation. He often noticed this fair-skinned dude who runs at the same time nodding his head at him but he didn’t want to start something he couldn’t finish.</p><p>But the dude started it. He let go of the nodding and suddenly started trying to outrun him every morning. Jerome found that to be a challenge and he took Chimdi on. Without speaking to each other every morning, they would appear at the same time and like an imaginary gun was shot into the air to mark the start of the race, both guys would take off each with the intent to beat the other.</p><p>This run-play continued with no apparent winner until a golden opportunity came to know the real champion.</p><p>Chimdi heard that the<strong><a href="http://www.armpension.com/rftf">ARM Pension Run For The Future</a></strong>&nbsp;was back and slated for November 30, 2019, and he figured that this was it. He spoke to Jerome for the first time and they both agreed to attend the run together and check who would finish first. So they registered for the run.</p><p>In speaking about the run, these two stubborn-heads discovered they had a lot in common. Soon, they were practising together ahead of the run and Jerome even started enjoying gisting while running.</p><p>He learnt two lessons with this incident. One, having a fitness buddy can sometimes be a good motivation and secondly, he got to know about the coolest run/walk event to end the year and could win loads of great prizes if he comes out tops.</p><p><strong><em>You could win prizes too but you have to register to run for free at <a href="http://www.armpension.com/rftf">www.armpension.com/rftf</a> . Go ahead and invite your fitness buddies – the more, the merrier!</em></strong></p><p>&nbsp;</p></div> <div><button class="btn btn-small bg-claret text-white mt-3"><i class="fa fa-arrow-alt-circle-left px-3"></i> Back to Posts</button></div></div></div></div></div>

@endsection